[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.install]
cmds = ["npm install --legacy-peer-deps"]

[build.nixpacksPlan.commands]
build = "npm run build"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"